#ifndef DEFINE_H
#define DEFINE_H

/* common */

#define VERSION "0.1"

#ifndef DEBUG 
	#define DEBUG 0
#endif

/* status */

#define STATUS_FAILURE 1
#define STATUS_SUCCESS 0

/* Inputs */

#define INPUT_BAD_PARAM 10

/* actions */

#define ACTION_INVALID 100
#define ACTION_GET 101
#define ACTION_STORE 102
#define ACTION_DELETE 103
#define ACTION_EXISTS 104
#define ACTION_SCAN 105

/* file type */

#define TYPE_UNKNOWN 200
#define TYPE_FILE 201
#define TYPE_DIR 202

/* shared memory */

#define SHM_MAX_SHARED_MEMORY_SIZE 1024
#define SHM_ERROR_OPEN 301
#define SHM_ERROR_TRUNCATE 302
#define SHM_ERROR_MMAP 303
#define SHM_ERROR_STAT 304
#define SHM_ERROR_DELETE 305
#define SHM_ERROR_FETCH 306
#define SHM_ERROR_MUNMAP 307
#define SHM_ERROR_NOT_FOUND 308
#define SHM_ERROR_FOUND 309

/* infile search */

#define INFILE_SEARCH_DEFAULT_MAX_CHAR 1024
#define INFILE_SEARCH_DEFAULT_FILENAME "index.html"

#define INFILE_SEARCH_ERROR_OPENDIR 401
#define INFILE_SEARCH_ERROR_READDIR 402

/* read config */

#define CONFIG_DELIM "="
#define CONFIG_DEFAULT_BUFFER 256
#define CONFIG_DEFAULT_LIMIT 1024

#define CONFIG_STRUCT_SEARCH_DIR "search_dir"
#define CONFIG_STRUCT_ACTION "action"
#define CONFIG_STRUCT_LIMIT "limit"
#define CONFIG_STRUCT_READ_BUFFER "read_buffer"
#define CONFIG_STRUCT_OUTPUT "output"
#define CONFIG_STRUCT_SEARCH_FILE "search_file"

#define CONFIG_VALID_ACTION_SCAN "scan"
#define CONFIG_VALID_ACTION_GET "get"
#define CONFIG_VALID_OUTPUT_SCREEN "screen"
#define CONFIG_VALID_OUTPUT_FILE "file"

#define CONFIG_ERROR_FILE_READ 501
#define CONFIG_ERROR_FILE_OPEN 502
#define CONFIG_ERROR_BAD_CONFIG_DIR 503
#define CONFIG_ERROR_BAD_CONFIG_ACTION 504
#define CONFIG_ERROR_BAD_CONFIG_LIMIT 505
#define CONFIG_ERROR_BAD_CONFIG_BUFFER 506
#define CONFIG_ERROR_BAD_CONFIG_OUTPUT 507

/* END */

#endif
